#!/bin/bash
 
echo "Installing CPU Power Management scripts..."
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo "Installing one-shot script..."
rsync -av ./scripts/usr /

echo "Installing event-triggered and service files..."
rsync -av ./scripts/etc /

echo "Restarting systemd daemon..."
systemctl daemon-reload

echo "Enabling service..."
systemctl enable switch_cpu_perf_mode.service

echo "Starting service..."
systemctl start switch_cpu_perf_mode.service

echo "Done."
