#!/bin/sh

echo "Installing powersave scripts..."
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

rsync -av ./scripts/etc /
cp ./scripts/switch_cpu_perf_mode /usr/local/bin

sed -i '/@reboot \/usr\/local\/bin\/switch_cpu_perf_mode/d' /var/spool/cron/crontabs/root
echo "@reboot sleep 5 && /home/bbarrois/.scripts/switch_cpu_perf_mode.sh" >> /var/spool/cron/crontabs/root

echo "Done. Please reboot."
