#!/bin/sh

echo "Uninstalling CPU powersave scripts..."
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

rm /etc/acpi/switch-to-ac
rm /etc/acpi/switch-to-battery
rm /etc/acpi/events/switch-to-ac
rm /etc/acpi/events/switch-to-battery
rm /usr/local/bin/switch_cpu_perf_mode

sed -i '/@reboot \/usr\/local\/bin\/switch_cpu_perf_mode/d' /var/spool/cron/crontabs/root

echo "Done. Please reboot."
